#!/bin/bash

echo "=== 변환 전 예시 ==="
echo "// then"
echo "assertThat(result).isNotNull();"
echo ""
echo "→ 1개만 있으면 그대로 유지"
echo ""
echo "=== 변환 전 예시 2 ==="
echo "// then"
echo "assertThat(result.id()).isEqualTo(1L);"
echo "assertThat(result.name()).isEqualTo(\"test\");"
echo ""
echo "→ 2개 이상이면 assertAll()로 변환:"
echo ""
echo "=== 변환 후 ==="
echo "// then"
echo "assertAll("
echo "        () -> assertThat(result.id()).isEqualTo(1L),"
echo "        () -> assertThat(result.name()).isEqualTo(\"test\")"
echo ");"
