server:
  port: 8080
  url: http://${SERVER_HOST}:${SERVER_PORT}

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      url: redis://${REDIS_HOST}:${REDIS_PORT}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST}:${KAFKA_SERVER_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

swagger:
  title: Dataracy
  description: Dataracy 백엔드 API 개발 문서입니다
  version: v1.2.0
  server-url: http://${SERVER_HOST}:8083
  server-description: develop server

elasticsearch:
  host: http://${ELASTIC_SEARCH_HOST}:${ELASTIC_SEARCH_PORT}
