server:
  port: 8080
  url: http://${SERVER_HOST}:${SERVER_PORT}

spring:
  application:
    name: dataracy-dev
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      url: redis://${REDIS_HOST}:${REDIS_PORT}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST}:${KAFKA_SERVER_PORT}

swagger:
  title: Dataracy
  description: Dataracy 백엔드 API 개발 문서입니다
  version: v1.2.0
  server-url: http://dataracy.store
  server-description: develop server

elasticsearch:
  connection:
    host: ${ELASTIC_SEARCH_HOST}
    port: ${ELASTIC_SEARCH_PORT}
    protocol: http
    ssl: false

logging:
  level:
    root: info
    org.springframework.web: debug

management:
  metrics:
    tags:
      application: dataracy-dev
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
