server:
  port: 8080
  url: https://dev.api.dataracy.co.kr

spring:
  application:
    name: dataracy-dev
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: ${REDIS_PROTOCOL}://${REDIS_HOST}:${REDIS_PORT}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      protocol: ${REDIS_PROTOCOL}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST}:${KAFKA_SERVER_PORT}

swagger:
  title: Dataracy
  description: Dataracy 백엔드 API 개발 문서입니다
  version: v1.2.0
  server-url: https://dev.api.dataracy.co.kr
  server-description: develop server

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

elasticsearch:
  connection:
    host: ${ELASTIC_SEARCH_HOST}
    port: ${ELASTIC_SEARCH_PORT}
    protocol: http
    ssl: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO
    org.springframework: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
    com.dataracy.modules.behaviorlog: DEBUG
    com.dataracy.modules.behaviorlog.support.aop.DataAccessLatencyAspect: INFO
    com.dataracy.modules.common.logging: INFO

management:
  metrics:
    tags:
      application: dataracy-dev
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
