server:
  port: 8080
  url: http://${SERVER_HOST}:${SERVER_PORT}

spring:
  application:
    name: dataracy-prod
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      url: redis://${REDIS_HOST}:${REDIS_PORT}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST}:${KAFKA_SERVER_PORT}

logging:
  level:
    root: warn

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

swagger:
  title: Dataracy
  description: Dataracy 백엔드 API 운영 문서입니다
  version: v1.2.0
  server-url: http://${SERVER_HOST}:${SERVER_PORT}
  server-description: prod server

  metrics:
    tags:
      application: dataracy-prod
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

elasticsearch:
  host: ${ELASTIC_SEARCH_HOST}
  port: ${ELASTIC_SEARCH_PORT}
  protocol: http
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  ssl: false
