server:
  port: 8080
  url: http://${SERVER_HOST}:${SERVER_PORT}

spring:
  config:
    import: "optional:file:.env[.properties]"
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      url: redis://${REDIS_HOST}:${REDIS_PORT}
      host: localhost
      port : 6380
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST}:${KAFKA_SERVER_PORT}

swagger:
  title: Dataracy
  description: Dataracy 백엔드 API 로컬 문서입니다
  version: v1.2.0
  server-url: http://${SERVER_HOST}:${SERVER_PORT}
  server-description: local server

elasticsearch:
  host: ${ELASTIC_SEARCH_HOST}
  port: ${ELASTIC_SEARCH_PORT}
#  username: elastic # → x-pack 보안 사용 시
#  password: your-password
  ssl: false
