server:
  port: 8080
  url: https://api.dataracy.co.kr

spring:
  application:
    name: dataracy-prod
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: ${REDIS_PROTOCOL}://${REDIS_HOST}:${REDIS_PORT}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      protocol: ${REDIS_PROTOCOL}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_HOST}:${KAFKA_SERVER_PORT}

logging:
  level:
    root: INFO
    org.hibernate: WARN
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    org.springframework: WARN
    org.apache.kafka: ERROR
    org.springframework.kafka: WARN
    com.dataracy.modules.behaviorlog: INFO
    com.dataracy.modules.behaviorlog.support.aop.DataAccessLatencyAspect: INFO
    com.dataracy.modules.common.logging: INFO

management:
  metrics:
    tags:
      application: dataracy-prod
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

springdoc:
  swagger-ui: { enabled: true }
  api-docs:   { enabled: true }

swagger:
  title: Dataracy
  description: Dataracy 백엔드 API 운영 문서입니다
  version: v1.2.0
  server-url: https://api.dataracy.co.kr
  server-description: prod server

elasticsearch:
  connection:
    host: ${ELASTIC_SEARCH_HOST}
    port: ${ELASTIC_SEARCH_PORT}
    protocol: http
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    ssl: false
