version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dev
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-dev-data:/var/lib/grafana
    networks:
      - monitor

networks:
  monitor:
    driver: bridge

volumes:
  grafana-dev-data:
