global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dataracy-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - "${BACKEND_SERVICE_HOST}:8081"
