services:
  redis-prod:
    image: redis:7.2
    container_name: redis-prod
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dataracy-network

networks:
  dataracy-network:
    external: true
