services:
  redis-local:
    image: redis:7.2
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dataracy-network

networks:
  dataracy-network:
    external: true