services:
  nginx-proxy-dev:
    image: nginx:1.25
    container_name: nginx-proxy-dev
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/upstream-blue-green-dev.conf:/etc/nginx/conf.d/upstream.conf:ro
      - /home/ubuntu/ssl/cloudflare:/etc/nginx/ssl/cloudflare:ro # SSL 인증서/키
    networks:
      - dataracy-network-dev

networks:
  dataracy-network-dev:
    external: true
