version: '3.8'

services:
  backend-green-dev:
    image: juuuunny/backend:latest
    container_name: backend-green-dev
    restart: always
    env_file:
      - /home/ubuntu/env-config/.env.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - dataracy-network-dev

networks:
  dataracy-network-dev:
    external: true
