services:
  backend-green:
    image: juuuunny/backend:green
    container_name: backend-green
    restart: always
    networks:
      - dataracy-network-dev
    ports:
      - "8082:8080"
    env_file:
      - /home/ubuntu/env-config/.env.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/upstream-blue-green-dev.conf:/etc/nginx/conf.d/upstream-blue-green.conf:ro
    networks:
      - dataracy-network-dev

networks:
  dataracy-network-dev:
    external: true
