services:
  backend-dev-blue:
    image: juuuunny/backend:dev-blue
    container_name: backend-dev-blue
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - /home/ubuntu/env-config/.env.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 120s
    networks:
      - dataracy-network-dev

networks:
  dataracy-network-dev:
    external: true