services:
  backend-blue:
    image: juuuunny/backend:blue
    container_name: backend-blue
    restart: always
    env_file: [/home/ubuntu/env-config/.env.dev]
    environment:
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks: [dataracy-network-dev]
    depends_on: []

networks:
  dataracy-network-dev:
    external: true
