version: "3.8"

services:
  backend-dev:
    image: juuuunny/backend:develop
    container_name: backend-dev
    ports:
      - "8083:8080"
    volumes:
      - /home/ubuntu/dataracy-dev/config/application-dev.yml:/app/application.yml:ro
    restart: always
    networks:
      - dataracy-dev-network

networks:
  dataracy-dev-network:
    driver: bridge
