version: '3.8'

services:
  backend-develop:
    image: juuuunny/backend:develop
    container_name: backend-develop
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - /home/ubuntu/dataracy/config/application-dev.yml:/app/application.yml:ro
    restart: unless-stopped
