services:
  backend-dev:
    image: juuuunny/backend:develop
    container_name: backend-dev
    restart: always
    ports:
      - "8083:8080"
    env_file:
      - /home/ubuntu/dataracy-dev/config/.env.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - dataracy-dev-network

networks:
  dataracy-dev-network:
    driver: bridge
    external: true
