services:
  backend-dev:
    image: juuuunny/backend:develop
    container_name: backend-dev
    network_mode: host
    restart: always
    env_file:
      - /home/ubuntu/dataracy-dev/config/.env.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
