version: '3.8'

services:
  backend-green:
    image: dataracy/backend:green
    container_name: backend-green
    restart: always
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dataracy-network

networks:
  dataracy-network:
    external: true
