services:
  backend-dev:
    image: juuuunny/backend:develop
    container_name: backend-dev
    restart: always
    ports:
      - "8083:8080"
    env_file:
      - /home/ubuntu/dataracy-dev/config/.env.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - dataracy-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 10

networks:
  dataracy-network:
    external: true
