version: '3.8'

services:
  backend-blue:
    image: juuuunny/backend:green
    container_name: backend-green
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - /home/ubuntu/dataracy/config/application.yml:/app/application.yml:ro
    networks:
      - dataracy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/dataracy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/dataracy/nginx/upstream-blue-green.conf:/etc/nginx/conf.d/upstream-blue-green.conf:ro
      - /etc/letsencrypt/live/dataracy.co.kr/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/dataracy.co.kr/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - dataracy-network

networks:
  dataracy-network:
    driver: bridge
