services:
  backend-dev:
    image: juuuunny/backend:develop
    container_name: backend-dev
    restart: always
    networks:
      - dataracy-network
    ports:
      - "8083:8080"
    env_file:
      - /home/ubuntu/env-config/.env.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev

  nginx:
    image: nginx:latest
    container_name: nginx-proxy-dev
    restart: always
    ports:
      - "8084:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/upstream-dev.conf:/etc/nginx/conf.d/upstream-dev.conf:ro
    networks:
      - dataracy-network

networks:
  dataracy-network:
    external: true
