version: '3.8'

services:
  backend-green:
    image: dataracy/backend:green
    container_name: backend-green
    restart: always
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dataracy-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/upstream-blue-green.conf:/etc/nginx/conf.d/upstream-blue-green.conf:ro
      - ../ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ../ssl/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - backend-blue
    networks:
      - dataracy-network

networks:
  dataracy-network:
    driver: bridge
