services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper-dev
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-dev:2888:3888;2181
    networks:
      - dataracy-network-dev

  kafka:
    image: apache/kafka:3.4.1
    container_name: kafka-dev
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-dev:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-dev:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    depends_on:
      - zookeeper
    networks:
      - dataracy-network-dev

networks:
  dataracy-network-dev:
    external: true
