services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-prod
    ports:
      - "2181:2181" # 내부 접근만 허용
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - dataracy-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-prod
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-prod:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-prod:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dataracy-network

networks:
  dataracy-network:
    external: true
