services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch-dev
    volumes:
      - elasticsearch-dev-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9201:9200"
    networks:
      - dataracy-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana-dev
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-dev:9200
    ports:
      - "5602:5601"
    networks:
      - dataracy-network
    depends_on:
      - elasticsearch

networks:
  dataracy-network:
    external: true

volumes:
  elasticsearch-dev-data:
    driver: local
