services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch-dev
    volumes:
      - elasticsearch-dev-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    # 개발 환경에서도 포트 노출 제거 (내부 네트워크만 사용)
    # ports:
    #   - "9200:9200"
    networks:
      - dataracy-network-dev

networks:
  dataracy-network-dev:
    external: true

volumes:
  elasticsearch-dev-data:
    driver: local
