services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ELASTIC_XPACK_ENABLED}
    ports:
      - "9201:9200"
    env_file:
      - /home/ubuntu/env-config/.env.dev
    networks:
      - dataracy-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana-dev
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-dev:9200
    ports:
      - "5602:5601"
    networks:
      - dataracy-network
    depends_on:
      - elasticsearch-dev

networks:
  dataracy-network:
    external: true
