services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch-prod
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ELASTIC_XPACK_ENABLED}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
    env_file:
      - /home/ubuntu/env-config/.env.prod
    networks:
      - dataracy-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana-prod
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-prod:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    env_file:
      - /home/ubuntu/env-config/.env.prod
    networks:
      - dataracy-network
    depends_on:
      - elasticsearch-prod

networks:
  dataracy-network:
    external: true
