name: Build and Push Docker Image (Dev Only)

on:
  pull_request:
    branches: [ develop ]

env:
  IMAGE_NAME: juuuunny/backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew clean build -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup SSH Agent for EC2 access
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.EC2_DEV_SSH_KEY }}" | ssh-add -
          mkdir -p ~/.ssh
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Determine TAG_NAME from dev server color
        run: |
          COLOR=$(ssh ubuntu@${{ secrets.EC2_DEV_HOST }} "cat ~/dataracy/deployment/dev/blue-green/current_color || echo blue")
          echo "Detected color: $COLOR"
          echo "TAG_NAME=develop-${COLOR}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          echo "📦 Building Docker image with tag: $TAG_NAME"
          docker build -t "${IMAGE_NAME}:${TAG_NAME}" -f Dockerfile .
          docker push "${IMAGE_NAME}:${TAG_NAME}"
