name: Build and Push Docker Image (PROD - latest only)

on:
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: juuuunny/backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: 🏗️ Build Application (Tests run in separate workflow)
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with SHA
        run: docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" .

      - name: Push Docker image (sha only)
        run: |
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"
