name: Build and Push Docker Image (DEV PR)

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  IMAGE_NAME: juuuunny/backend
  IMAGE_TAG: dev-ci-${{ github.sha }}

jobs:
  build-and-push:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    concurrency:
      group: dev-pr-${{ github.event.pull_request.head.sha }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}"
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: "Build Spring Boot app (skip tests)"
        run: ./gradlew clean build -x test

      - name: "Log in to Docker Hub"
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build image (tag: sha)"
        run: |
          docker build --pull -t "${IMAGE_NAME}:${IMAGE_TAG}" .

      - name: "Push image (skip on forks)"
        if: ${{ !github.event.pull_request.head.repo.fork }}
        run: |
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"

      - name: "Note about forks (no push)"
        if: ${{ github.event.pull_request.head.repo.fork }}
        run: |
          echo 'Fork PR: built image locally but skipped Docker Hub push.'
