name: Deploy Develop to EC2

on:
  push:
    branches: [ develop ]

env:
  IMAGE_NAME: juuuunny/backend

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Save PEM key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2key.pem
          chmod 600 ec2key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dataracy-dev
            git reset --hard
            git clean -fd
            git fetch origin develop
            git checkout develop
            git reset --hard origin/develop
            docker pull juuuunny/backend:develop
            docker compose -f deployment/docker/docker-compose-dev.yml down --remove-orphans
            docker compose -f deployment/docker/docker-compose-dev.yml up -d
