name: Deploy to EC2 (Development - Blue/Green)

on:
  push:
    branches: [ develop ]

env:
  IMAGE_NAME: juuuunny/backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Save PEM key
        run: |
          echo "${{ secrets.EC2_DEV_SSH_KEY }}" > ec2key.pem
          chmod 600 ec2key.pem

      - name: Get DEPLOY_COLOR from DEV EC2
        run: |
          COLOR=$(ssh -o StrictHostKeyChecking=no -i ec2key.pem ubuntu@${{ secrets.EC2_DEV_HOST }} "cat ~/dataracy/server/deployment/dev/blue-green/current_color || echo blue")
          if [ "$COLOR" = "blue" ]; then
            echo "DEPLOY_COLOR=green" >> $GITHUB_ENV
            echo "PREVIOUS_COLOR=blue" >> $GITHUB_ENV
          else
            echo "DEPLOY_COLOR=blue" >> $GITHUB_ENV
            echo "PREVIOUS_COLOR=green" >> $GITHUB_ENV
          fi

      - name: Pull & Deploy to DEV EC2 (Blue/Green)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_DEV_SSH_KEY }}
          script: |
            cd ~/dataracy
            git reset --hard
            git clean -fd
            git fetch origin develop
            git reset --hard origin/develop
            chmod +x server/deployment/dev/script/deploy.sh
            ./server/deployment/dev/script/deploy.sh
