name: Build and Deploy to EC2 (Blue/Green)

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: juuuunny/backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Save PEM key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2key.pem
          chmod 600 ec2key.pem

      - name: Set Docker tag based on branch
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            COLOR=$(ssh -o StrictHostKeyChecking=no -i ec2key.pem ubuntu@${{ secrets.EC2_HOST }} "cat ~/dataracy/deployment/blue-green/current_color || echo blue")
            if [ "$COLOR" = "blue" ]; then
              echo "TAG_NAME=green" >> $GITHUB_ENV
            else
              echo "TAG_NAME=blue" >> $GITHUB_ENV
            fi
          else
            echo "TAG_NAME=develop" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG_NAME -f Dockerfile .
          docker push $IMAGE_NAME:$TAG_NAME
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Save PEM key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2key.pem
          chmod 600 ec2key.pem

      - name: Get DEPLOY_COLOR from EC2
        run: |
          COLOR=$(ssh -o StrictHostKeyChecking=no -i ec2key.pem ubuntu@${{ secrets.EC2_HOST }} "cat ~/dataracy/deployment/blue-green/current_color || echo blue")
          if [ "$COLOR" = "blue" ]; then
            echo "DEPLOY_COLOR=green" >> $GITHUB_ENV
            echo "PREVIOUS_COLOR=blue" >> $GITHUB_ENV
          else
            echo "DEPLOY_COLOR=blue" >> $GITHUB_ENV
            echo "PREVIOUS_COLOR=green" >> $GITHUB_ENV
          fi

      - name: Pull Image and Deploy to EC2 (Blue/Green)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dataracy
            git reset --hard
            git clean -fd
            git fetch origin main
            git reset --hard origin/main
            chmod +x deployment/script/deploy.sh
            ./deployment/script/deploy.sh
