name: Build and Deploy to EC2 (Blue/Green)

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: juuuunny/backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Save PEM key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2key.pem
          chmod 600 ec2key.pem

      - name: Get DEPLOY_COLOR from EC2
        run: |
          COLOR=$(ssh -o StrictHostKeyChecking=no -i ec2key.pem ubuntu@${{ secrets.EC2_HOST }} "cat ~/dataracy/deployment/blue-green/current_color || echo blue")
          if [ "$COLOR" = "blue" ]; then
            echo "DEPLOY_COLOR=green" >> $GITHUB_ENV
            echo "PREVIOUS_COLOR=blue" >> $GITHUB_ENV
          else
            echo "DEPLOY_COLOR=blue" >> $GITHUB_ENV
            echo "PREVIOUS_COLOR=green" >> $GITHUB_ENV
          fi

      - name: Pull Image and Deploy to EC2 (Blue/Green)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dataracy
            git reset --hard
            git clean -fd
            git fetch origin main
            git reset --hard origin/main
            chmod +x deployment/script/deploy.sh
            ./deployment/script/deploy.sh
