name: Build and Deploy to EC2 (Blue/Green)

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: juuuunny/backend
  DEPLOY_COLOR: green  # 🔄 추후 자동 전환 로직 적용 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ env.DEPLOY_COLOR }} \
                       -t $IMAGE_NAME:${{ github.sha }} \
                       -t $IMAGE_NAME:latest \
                       -f deployment/docker/Dockerfile .
          docker push $IMAGE_NAME:${{ env.DEPLOY_COLOR }}
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      - name: Deploy to EC2 (Blue/Green)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dataracy
            git pull origin main
            chmod +x deployment/script/deploy.sh
            ./deployment/script/deploy.sh
