name: Deploy Develop to EC2

on:
  push:
    branches: [ develop ]

env:
  IMAGE_NAME: juuuunny/backend

jobs:
  deploy-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Save PEM key to file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2key.pem
          chmod 600 ec2key.pem

      - name: Build and Push Develop Docker Image
        run: |
          docker build -t $IMAGE_NAME:develop -f Dockerfile .
          docker push $IMAGE_NAME:develop

      - name: SSH to EC2 and Deploy Develop Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dataracy-dev
            git fetch origin develop
            git checkout develop
            git reset --hard origin/develop
            docker pull juuuunny/backend:develop
            git clean -fd
            docker compose -f deployment/docker/docker-compose-dev.yml down
            docker compose -f deployment/docker/docker-compose-dev.yml up -d